# SETTING
STOPWATCH_TIME = 5
ICON_NAME = "brain.png"

# PATH
IMAGE_PATH = "./venv/Component/Images/"
ICON_PATH = "./venv/Component/Icons/"

# WINDOW
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_X = 300
WINDOW_Y = 300

# BUTTON
BUTTON_WIDTH = 80
BUTTON_HEIGHT = 25
BUTTON_MARGIN = 10
START_BUTTON_X = (WINDOW_WIDTH-BUTTON_WIDTH)/2
START_BUTTON_Y = WINDOW_HEIGHT - (BUTTON_HEIGHT + BUTTON_MARGIN)
