# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memoryGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import threading

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QColor, QPen, QPainter, QPixmap, QIcon
from PyQt5.QtWidgets import QLabel

from constant import *

global level
global time


class Ui_Dialog(object):
    level = 0

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(WINDOW_WIDTH, WINDOW_HEIGHT)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, WINDOW_WIDTH, 31))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background: rgb(255, 255, 255)")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("level_label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 0, WINDOW_WIDTH, 80))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("time_label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 70, 521, 300))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(START_BUTTON_X, START_BUTTON_Y, BUTTON_WIDTH, BUTTON_HEIGHT))
        self.startButton.setObjectName("startButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        global level
        level = 0
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "기억력 테스트"))
        Dialog.setWindowIcon(QIcon(ICON_PATH + ICON_NAME))
        self.label.setText(_translate("Dialog", "Level " + str(level)))
        self.label_2.setText(_translate("Dialog", str(STOPWATCH_TIME)))
        self.startButton.setText(_translate("Dialog", "시작"))
        self.startButton.clicked.connect(self.startButtonClicked)

    def startButtonClicked(self):
        global level
        level = level + 1

        global time
        time = STOPWATCH_TIME

        self.label.setText("Level " + str(level))

        self.setGameBoard()

        def stopwatchProcess():
            global time

            self.label_2.setText(str(time))

            schedule = threading.Timer(1, stopwatchProcess)
            schedule.start()

            if time == 0:
                schedule.cancel()

            time -= 1

        stopwatchProcess()

    def setGameBoard(self):
        global level
        image_list = getImageList()

        for i in range(level + 1):
            image_name = image_list.__getitem__(i)
            self.drawImageLabel(image_name)

        # self.testLabel = QtWidgets.QLabel(Dialog)
        # pixmap = QPixmap("banana.png")
        # self.testLabel.setPixmap(pixmap)
        # self.testLabel.setAlignment(Qt.AlignCenter)
        # self.formLayout.addWidget(self.testLabel)
        # self.testLabel.setGeometry(QtCore.QRect(230, 500, 75, 23))

    def drawImageLabel(self, image_name):
        print("draw starting ...")
        for i in range(2):
            self.image_label = QtWidgets.QLabel(Dialog)
            pixmap = QPixmap(IMAGE_PATH + image_name)
            self.image_label.setPixmap(pixmap)
            self.image_label.setAlignment(Qt.AlignCenter)
            object_name = image_name.replace(".png", "")
            self.image_label.setObjectName(object_name)
            self.formLayout.addWidget(self.image_label)
            print(self.image_label.objectName())
        # self.testLabel.setGeometry(QtCore.QRect(230, 500, 75, 23))


# Get Resource
def getImageList():
    print('image load start ...')
    imageList = os.listdir(IMAGE_PATH)
    return imageList

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
